services:
  mysql_db:
    image: "mysql:latest"
    restart: always
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: "my-secret-pw"
      MYSQL_DATABASE: "testing"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 --password=$$MYSQL_ROOT_PASSWORD
      timeout: 60s
      retries: 10
      interval: 1s

  postgres_db:
    image: "postgres:latest"
    restart: always
    cap_add:
      - SYS_NICE
    environment:
      POSTGRES_PASSWORD: "my-secret-pw"
    healthcheck:
      test: pg_isready -q -d postgres -U postgres
      timeout: 60s
      retries: 10
      interval: 1s

  sqlsrv_db:
    image: "mcr.microsoft.com/mssql/server"
    restart: always
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Your_password123 -Q "SELECT 1" || exit 1
      timeout: 60s
      retries: 10
      interval: 1s

  mysql:
    image: lodata:php81
    volumes:
      - .:/lodata
    environment:
      - DATABASE_URL=mysql://root:my-secret-pw@mysql_db:3306/testing
    entrypoint: "composer test"
    depends_on:
      mysql_db:
        condition: service_healthy

  postgres:
    image: lodata:php81
    volumes:
      - .:/lodata
    environment:
      - DATABASE_URL=pgsql://postgres:my-secret-pw@postgres_db:5432/postgres?charset=utf8
    entrypoint: "composer test"
    depends_on:
      postgres_db:
        condition: service_healthy

  sqlsrv:
    image: lodata:php81
    volumes:
      - .:/lodata
    environment:
      - DATABASE_URL=sqlsrv://sa:Your_password123@sqlsrv_db:1433/msdb
    entrypoint: "composer test"
    depends_on:
      sqlsrv_db:
        condition: service_healthy

  php73:
    image: lodata:php73
    volumes:
      - .:/lodata
    build:
      args:
        - ALPINE=3.12
        - PHP=7
    entrypoint: "/bin/sh -c 'composer update && composer test'"

  php74:
    image: lodata:php74
    volumes:
      - .:/lodata
    build:
      args:
        - ALPINE=3.15
        - PHP=7
    entrypoint: "/bin/sh -c 'composer update && composer test'"

  php80:
    image: lodata:php80
    volumes:
      - .:/lodata
    build:
      args:
        - ALPINE=3.15
        - PHP=8
    entrypoint: "/bin/sh -c 'composer update && composer test'"

  php81:
    image: lodata:php81
    volumes:
      - .:/lodata
    build:
      args:
        - ALPINE=edge
        - PHP=81
    entrypoint: "composer test"

  update:
    image: lodata:php81
    volumes:
      - .:/lodata
    entrypoint: "composer update"

  analyse:
    image: lodata:php81
    volumes:
      - .:/lodata
    entrypoint: "composer analyse"

  coverage:
    image: lodata:php81
    volumes:
      - .:/lodata
    environment:
      - CC_TEST_REPORTER_ID=1be98f680ca97065e8a18ad2df18e67210033bb0708b5b70e4d128b035b0cb45
    entrypoint: "/bin/sh -c 'composer coverage && cc-reporter after-build -t clover --exit-code $$?'"
