name: Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    types: [ ready_for_review, synchronize, opened ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        container: [ mysql, sqlsrv, postgres, php73, php74, php80, php81 ]

    name: Test ${{ matrix.container }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        run: docker compose run ${{ matrix.container }} && docker compose down

  analysis:
    runs-on: ubuntu-latest
    name: Analysis

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run analysis
        run: docker compose run analyse && docker compose down

  coverage:
    runs-on: ubuntu-latest
    name: Coverage

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run coverage
        run: docker compose run -e GIT_BRANCH=`git branch --show-current` -e GIT_COMMIT_SHA=`git rev-parse HEAD` -e GIT_COMMITTED_AT=`git log -1 --pretty=format:%ct` coverage && docker compose down
