name: Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    types: [ ready_for_review, synchronize, opened ]

jobs:
  php81:
    runs-on: ubuntu-latest
    name: PHP 8.1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: docker-compose up --exit-code-from php81 php81

      - name: Static analysis
        run: docker-compose up --exit-code-from analyse analyse

      - name: MySQL
        run: docker-compose up --exit-code-from mysql mysql

      - name: SQL Server
        run: docker-compose up --exit-code-from sqlsrv sqlsrv

      - name: PostgreSQL
        run: docker-compose up --exit-code-from postgres postgres

      - name: Test Coverage
        run: docker-compose up --exit-code-from coverage coverage

      - name: Shutdown
        run: docker-compose down

  php73:
    runs-on: ubuntu-latest
    name: PHP 7.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: docker-compose up --exit-code-from php73 php73

  php74:
    runs-on: ubuntu-latest
    name: PHP 7.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: docker-compose up --exit-code-from php74 php74

  php80:
    runs-on: ubuntu-latest
    name: PHP 8.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: docker-compose up --exit-code-from php80 php80
