name: Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    types: [ ready_for_review, synchronize, opened ]

jobs:
  php81:
    runs-on: ubuntu-latest
    name: PHP 8.1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: docker compose up php81

      - name: Update
        run: docker compose up update

      - name: Test
        run: docker compose up --exit-code-from test test

      - name: MySQL
        run: docker compose up --exit-code-from mysql mysql

      - name: SQL Server
        run: docker compose up --exit-code-from sqlsrv sqlsrv

      - name: PostgreSQL
        run: docker compose up --exit-code-from postgres postgres

      - name: Shutdown
        run: docker compose down

  php80:
    runs-on: ubuntu-latest
    name: PHP 8.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: docker compose up php80

      - name: Update
        run: docker compose up update

      - name: Test
        run: docker compose up --exit-code-from test test

  php74:
    runs-on: ubuntu-latest
    name: PHP 7.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: docker compose up php74

      - name: Update
        run: docker compose up update

      - name: Test
        run: docker compose up --exit-code-from test test

  php73:
    runs-on: ubuntu-latest
    name: PHP 7.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: docker compose up php73

      - name: Update
        run: docker compose up update

      - name: Test
        run: docker compose up --exit-code-from test test

  analysis:
    runs-on: ubuntu-latest
    name: Analysis

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: docker compose up php81

      - name: Update
        run: docker compose up update

      - name: Static analysis
        run: docker compose up --exit-code-from analyse analyse

      - name: Test Coverage
        run: GIT_COMMITTED_AT=`git log -1 --pretty=format:%ct` docker compose up --exit-code-from coverage coverage

      - name: Shutdown
        run: docker compose down