name: Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    types: [ ready_for_review, synchronize, opened ]

jobs:
  php81:
    runs-on: ubuntu-latest
    name: PHP 8.1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: docker compose up php81

      - name: Analyse
        run: docker compose up analyse

      - name: MySQL
        run: docker compose up mysql

      - name: SQL Server
        run: docker compose up sqlsrv

      - name: PostgreSQL
        run: docker compose up postgres

      - name: Test Coverage
        run: docker compose up -e GIT_BRANCH=`git branch --show-current` -e GIT_COMMIT_SHA=`git rev-parse HEAD` -e GIT_COMMITTED_AT=`git log -1 --pretty=format:%ct` coverage

      - name: Shutdown
        run: docker compose down

  php73:
    runs-on: ubuntu-latest
    name: PHP 7.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: php73
        run: docker compose up php73

  php74:
    runs-on: ubuntu-latest
    name: PHP 7.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: docker compose up php74

  php80:
    runs-on: ubuntu-latest
    name: PHP 8.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: docker compose up php80
