name: Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    types: [ ready_for_review, synchronize, opened ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: php81
        run: docker compose run php81

      - name: analysis
        run: docker compose run analyse

      - name: mysql
        run: docker compose run mysql

      - name: sqlsrv
        run: docker compose run sqlsrv

      - name: postgres
        run: docker compose run postgres

      - name: php73
        run: docker compose run php73

      - name: php73
        run: docker compose run php74

      - name: php80
        run: docker compose run php80

      - name: coverage
        run: docker compose run -e GIT_BRANCH=`git branch --show-current` -e GIT_COMMIT_SHA=`git rev-parse HEAD` -e GIT_COMMITTED_AT=`git log -1 --pretty=format:%ct` coverage

      - name: shutdown
        run: docker compose down