name: Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    types: [ ready_for_review, synchronize, opened ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [ 73, 74, 80, 81 ]
        laravel: [ 8, 9 ]
        database: [ sqlite, sqlsrv, postgres, mysql ]
        exclude:
          - php: 73
            laravel: 9
          - php: 74
            laravel: 9
    name: PHP:${{ matrix.php }} / Laravel:${{ matrix.laravel }} / Database:${{matrix.database}}
    env:
      PHP: ${{ matrix.php }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-

      - name: Install Composer dependencies
        run: |
          docker compose run require "laravel/framework:${{ matrix.laravel }}"
          docker compose up update

      - name: Run tests
        run: docker compose up --exit-code-from ${{ matrix.database }} ${{ matrix.database }}

      - name: Shutdown
        run: docker compose down

  analysis:
    runs-on: ubuntu-latest
    name: Analysis
    env:
      PHP: 81
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update
        run: docker compose up update

      - name: Static analysis
        run: docker compose up --exit-code-from analyse analyse

      - name: Test Coverage
        run: GIT_COMMITTED_AT=`git log -1 --pretty=format:%ct` docker compose up --exit-code-from coverage coverage